library(readxl)
library(writexl)
library(glue)
library(data.table)
library(caret)
library(randomForest)
library(ggplot2)
library(glmnet)
library(SGL)
library(doParallel)
library(jsonlite)
library(pROC)
library(ExPanDaR)
library(NbClust)
library(EMCluster)
library(magrittr)
library(parallel)
library(pracma)
library(mvnfast)
library(Rfast)
library(DMwR)
library(themis)
library(reshape2)
library(rlang)
library(gglasso)

path_data <- "../data"

df <- read_excel(glue("{path_data}/radiomiques_global.xlsx"))
print(length(df$classe_name))
df$key <- paste0(df$classe_name, df$patient_num)
print(length(unique(df[df$classe_name == "CCK", ]$key)))
