default:
  regression: TRUE
  tuneLength: 1
  n_lambda: 1

  n_centro_min: 20
  n_centro_max: 20
  dim_max: 2
  lambda_min: 0.001
  lambda_max: 0.001

  weights:
    "CCK": 1
    "CHC": 1

##### NB: in this model, weights are discarded if sampling is not NULL

my_config:

  # weights:
  #   "CCK": 4.5
  #   "CHC": 1

  #0.74 sur 20 ; 0.752083333333333" sur 40
