default:
  regression: TRUE


radio:
  #lambda: 0.1
  lambda_min: 0.00001
  lambda_max: 0.2
  tuneLength: 20

  weights:
    "CCK": 1
    "CHC": 1

simu:
  #lambda: 0.1
  lambda_min: 0.0000000000001
  lambda_max: 0.00001
  tuneLength: 10

  weights:
    "Classe_0": 1
    "Classe_1": 1


