default:
  regression: TRUE

radio:
  lambda_min: 0.001
  tuneLength: 10
  index_type: "var" #"bloc" , "mode" ou "var" : par quoi on groupe

simu:
  lambda_min: 0.001
  tuneLength: 20 
  index_type: "bloc" #"bloc" , "mode" ou "var" : par quoi on groupe


