default:
  regression: TRUE

radio:
  lambda_min: 0.000001
  lambda_max: 0.2
  tuneLength: 20

  weights:
    "CCK": 1
    "CHC": 1

radio_big:
  lambda_min: 0.0001
  lambda_max: 1
  tuneLength: 20

  weights:
    "CCK": 1
    "CHC": 1

simu:
  lambda_min: 0.0000000000001
  lambda_max: 0.00001
  tuneLength: 20

  weights:
    "Classe_0": 1
    "Classe_1": 1
