default:
  regression: TRUE
  eps: 0.00000001 #10^-8
  ite_max: 1000
  n_iter_per_reg: 50


radio:
  lambda_min: 0.00005
  lambda_max: 0.01
  R_min: 1
  R_max: 2 
  tuneLength: 1
  tune_R: 2
  same_R: TRUE

  weights:
    "CCK": 1
    "CHC": 1

simu:
  lambda_min: 0.000001
  lambda_max: 0.001
  R_min: 12
  R_max: 12
  same_R: FALSE
  li_R:
    block_1: [1,6,10]
    block_2: [1]
    block_3: [10]
  tuneLength: 3

  weights:
    "Classe_0": 1
    "Classe_1": 1








# R = 2; 20 iterations. AUC moyenne test 0.767361111111111", moyenne AUC val 0.751666666666667".
# R = 3; 20 iterations, AUC moyenne test 0.809722222222222, moyenne AUC val 0.731830808080808.
# R = 4; 20 iterations, AUC moyenne test ________________, moyenne AUC val ________________.

