default:
  regression: FALSE
  weights:
    "CCK": 1
    "CHC": 1

  mtry:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 7
    - 9
    - 11
    - 12
    - 13

my_config:
  # weights:
  #   "CCK": 4.5
  #   "CHC": 1

  # mtry:
  #   - 5
#0.66 #indep nombre variables...
