default:
  radio_col:
    - "diagnostics_Versions_PyRadiomics"
    - "diagnostics_Versions_SimpleITK"
    - "diagnostics_Image.original_Dimensionality"
    - "diagnostics_Image.interpolated_Spacing"
    - "diagnostics_Versions_Numpy"
    - "diagnostics_Versions_PyWavelet"
    - "diagnostics_Versions_Python"
    - "diagnostics_Image.original_Hash"
    - "diagnostics_Image.original_Minimum"
    - "diagnostics_Mask.interpolated_Spacing"
    - "diagnostics_Mask.original_Hash"

  patients_col:
    - "patient_num"
    - "classe_name"
    - "Gender"
    - "Age_at_disease"

  time_inj:
    - "ART_"
    - "PORT"
    - "VEIN"
    - "TARD"

  kill_empty: TRUE
  kill_outliers: TRUE

  include_products: FALSE

my_config:
  time_inj:
    - "ART_"
    - "PORT"
    - "TARD"
    #- "VEIN"

  kill_empty: TRUE
  kill_mixtes: TRUE
  first_order_only: FALSE #cata sur seed 8 multiway si TRUE: checker le group lasso
  include_products: FALSE

  shape_only: FALSE
  texture_only: FALSE

  other_only: FALSE #Pas de first order

  radio_col:
    - "diagnostics_Versions_PyRadiomics"
    - "diagnostics_Versions_SimpleITK"
    - "diagnostics_Image.original_Dimensionality"
    - "diagnostics_Image.interpolated_Spacing"
    - "diagnostics_Versions_Numpy"
    - "diagnostics_Versions_PyWavelet"
    - "diagnostics_Versions_Python"
    - "diagnostics_Image.original_Hash"
    - "diagnostics_Image.original_Minimum"
    - "diagnostics_Mask.interpolated_Spacing"
    - "diagnostics_Mask.original_Hash"
    - "diagnostics_Mask.original_VolumeNum"
    - "diagnostics_Mask.interpolated_VolumeNum"
    - "diagnostics_Mask.interpolated_BoundingBox"
    - "diagnostics_Image.interpolated_Minimum"
    - "Column1"
