default:
  include_products: FALSE
  num_picto:
    - 6
    - 1
    - 2
  n_sample: 1500
  resample: FALSE #ignoré pour l'instant
  ecart_class: 1 #ecart entre les moyennes des classes
  dist_sepa: 0.1
  dist_non_sepa: 0.5
  prop_class_1: 0.5
  do_QR: FALSE #Re-decomp QR ou non
  do_product: FALSE #recalculer sigma ou non

my_config:
