default:
  patients_col:
    - "patient_num"
    - "classe_name"
    - "Gender"
    - "Age_at_disease"

  time_inj:
    - "ART_"
    - "PORT"
    - "VEIN"
    - "TARD"

  kill_empty: TRUE
  kill_outliers: TRUE

  include_products: FALSE

my_config:
  time_inj:
    - "ART_"
    - "PORT"
    - "TARD"
    #- "VEIN"

  time_inj_sain_name:
    - "ART"
    - "PORT"
    - "TARD"
    #- "VEIN"

  kill_empty: TRUE
  kill_mixtes: TRUE
  include_products: FALSE

  first_order_only: FALSE
  shape_only: FALSE
  texture_only: FALSE
  other_only: FALSE #Pas de first order

  average_shape: TRUE
  compare_sain:
    do: FALSE
    first_order_only: FALSE

  kill_col:
    - "Column1"
