default:
  time_inj:
    - "ART"
    - "PORT"
    #- "VEIN"
    - "TARD"

  new_names_time_inj:
    - "ART_"
    - "PORT"
    #- "VEIN"
    - "TARD"

  patients_col:
    - "patient_num"
    - "classe_name"
    - "Gender"
    - "Age_at_disease"

  max_prop_consecutif_acceptable: 0.05
  max_prop_acceptable: 0.99
  #ici c'est à chaque fois la proportion d'absents acceptable
  kill_mixtes: TRUE
  kill_outliers: TRUE
  n_slices: 10
  strong_exclusion: FALSE #Est-ce que la présence d'une seule temporalité suffit à faire commencer la tumeur (TRUE = oui)

  shape_3D:
    do: TRUE
    average: TRUE

  shape_2D:
    do: TRUE
    average: TRUE

my_config:
