default:
  do_extract: TRUE
  extrac_first: TRUE
  simulated_data: FALSE
  num_runs: 1
  simple_generation: FALSE

my_config:
  do_extract: FALSE #réextraire ou non après la première fois
  extrac_first: TRUE #extraire ou non la toute première fois
  simulated_data: FALSE
  num_runs: 40
