default:
  do_extract: TRUE
  extrac_first: TRUE
  simulated_data: FALSE
  num_runs: 1
  simple_generation: FALSE
  keep_partition: FALSE
  nom_spe: "simu_modium_easy_var"

my_config:
  do_extract: FALSE #réextraire ou non après la première fois
  extrac_first: TRUE #extraire ou non la toute première fois
  simulated_data: TRUE
  big_data: FALSE #utiliser li_index_modes? et la big version des données si elle existe? Interdit sur simulmted_data!!
  num_runs: 1
