default:
  kill_mixtes_col:
  show_logs: TRUE
  calc_probs: TRUE

  k: 5
  p: 0.75 #Séparation entre train et test
  rep: 1
  k_smote: 3
  sampling: "up" # "up","smote", NULL
  search: "grid" #grid ou random
  parallel:
    do: TRUE
    n_process: 20
    forking: FALSE #useless
  analyse_data:
    do: FALSE
    EM: FALSE

  penalty_adapt: FALSE #Seulement sur logistique_simple

  do_multiway: TRUE
  #name_model: "logistique_simple"
  #name_model: "logistic_grp"
  name_model: "logistic_multibloc"

  #3 modèles trop vieux:
  #name_model: "logistic_select"
  #name_model: "random_forest"
  #name_model: "logistic_multiway"

radio:
  minimal_information: FALSE #pour tester
  classe_1: "CCK"

radio_big:
  minimal_information: FALSE
  classe_1: "CCK"

simu:
  minimal_information: FALSE
  classe_1: "Classe_1"
