default:
  kill_mixtes_col:
  show_logs: TRUE
  calc_probs: TRUE

  k: 5
  p: 0.75 #Séparation entre train et test
  rep: 1
  k_smote: 3
  sampling: "up" # "up","smote", NULL
  search: "grid" #grid ou random
  parallel: 
    do: FALSE
    n_process: 2
    forking: FALSE #useless
  analyse_data: 
    do: FALSE
    EM: FALSE
  

  #name_model: "logistique_simple"
  #name_model: "logistic_grp"
  #name_model: "logistic_multiway"
  name_model: "logistic_multibloc"

  #2 modèles trop vieux:
  #name_model: "logistic_select"
  #name_model: "random_forest" 


radio:
  minimal_information: FALSE
  classe_1: "CCK"


simu:
  minimal_information: FALSE
  classe_1: "Classe_1"

